// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ62hE_R3eUiy87VpZjNOHwjqufJ38cGw',
    appId: '1:360788632263:web:07d6b4526749a9ef2754e2',
    messagingSenderId: '360788632263',
    projectId: 'katomaran-5516b',
    authDomain: 'katomaran-5516b.firebaseapp.com',
    storageBucket: 'katomaran-5516b.firebasestorage.app',
    measurementId: 'G-SG0ZPFYV99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBi_kngE4iS0Z7e1eDWqF3Vm1XTTL7wU8',
    appId: '1:360788632263:android:b6fe7f43504a8a052754e2',
    messagingSenderId: '360788632263',
    projectId: 'katomaran-5516b',
    storageBucket: 'katomaran-5516b.firebasestorage.app',
  );
}
